/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_medialearn_LivePush */

#ifndef _Included_com_example_medialearn_LivePush
#define _Included_com_example_medialearn_LivePush
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_medialearn_LivePush
 * Method:    startPush
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_medialearn_LivePush_startPush
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_medialearn_LivePush
 * Method:    stopPush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_medialearn_LivePush_stopPush
  (JNIEnv *, jobject);

/*
 * Class:     com_example_medialearn_LivePush
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_medialearn_LivePush_release
  (JNIEnv *, jobject);

/*
 * Class:     com_example_medialearn_LivePush
 * Method:    setVideoOptions
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_medialearn_LivePush_setVideoSpsPps
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_example_medialearn_LivePush
 * Method:    setAudioOptions
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_medialearn_LivePush_setAudioOptions
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_medialearn_LivePush
 * Method:    sendVideoPacket
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_example_medialearn_LivePush_sendVideoPacket
  (JNIEnv *, jobject, jbyteArray, jint, jboolean);

/*
 * Class:     com_example_medialearn_LivePush
 * Method:    sendAudioPacket
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_example_medialearn_LivePush_sendAudioPacket
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
